### ISSUE TITLE
please go through this ERR! 

### ISSUE THREAD

**Issue by AusGirl** [didinj/node-express-mongoose-passport-jwt-rest-api-auth#12]
when npm start the following pops up

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rest-auth@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rest-auth@0.0.0 start script.
```

**Comment by didinj** [comment]
Step 1: `npm cache clean --force`

Step 2: Delete node_modules by `rm -rf node_modules` folder or delete it manually by going into the directory and right-click > delete/move to trash. If are not updating your packages you can delete the package-lock.json file too.

Step 3: `npm install`

To start again, `npm start `
